license="MIT License"
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
issueTrackerURL="https://github.com/CodenameRevy/Flesh2Leather/issues" #optional
[[mods]] #mandatory
modId="flesh2leather" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Flesh2Leather" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/CodenameRevy/Flesh2Leather" #optional
logoFile="logo.png" #optional
credits="CodenameRevy, lechiny" #optional
authors="CodenameRevy" #optional
description='''
This Mod adds a new Item called "Combined Flesh" that can be smoked into Leather!
'''
[[dependencies.flesh2leather]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.flesh2leather]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
